# -*- coding: utf-8 -*-

################################################################################
## File generated from reading UI file 'main.ui'
################################################################################

from PySide6.QtCore import (QCoreApplication,
    QMetaObject, QRect,
    QSize, Qt)
from PySide6.QtGui import (QAction,  QFont, QIcon, QPixmap)
from PySide6.QtWidgets import (QLabel, QMenu,
    QMenuBar, QPushButton, QSlider,
    QStatusBar, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(485, 620)
        MainWindow.setMinimumSize(QSize(485, 620))
        MainWindow.setMaximumSize(QSize(485, 620))
        MainWindow.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.actionOpenFile = QAction(MainWindow)
        self.actionOpenFile.setObjectName(u"actionOpenFile")
        icon = QIcon()
        icon.addFile(u":/assets/file.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpenFile.setIcon(icon)
        self.actionOpenFolder = QAction(MainWindow)
        self.actionOpenFolder.setObjectName(u"actionOpenFolder")
        icon1 = QIcon()
        icon1.addFile(u":/assets/folder.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpenFolder.setIcon(icon1)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon2 = QIcon()
        icon2.addFile(u":/assets/quit.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionQuit.setIcon(icon2)
        self.actionPlay = QAction(MainWindow)
        self.actionPlay.setObjectName(u"actionPlay")
        icon3 = QIcon()
        icon3.addFile(u":/assets/player-play.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPlay.setIcon(icon3)
        self.actionPrevious = QAction(MainWindow)
        self.actionPrevious.setObjectName(u"actionPrevious")
        icon4 = QIcon()
        icon4.addFile(u":/assets/player-skip-back.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrevious.setIcon(icon4)
        self.actionNext = QAction(MainWindow)
        self.actionNext.setObjectName(u"actionNext")
        icon5 = QIcon()
        icon5.addFile(u":/assets/player-skip-forward.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNext.setIcon(icon5)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon6 = QIcon()
        icon6.addFile(u":/assets/info.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAbout.setIcon(icon6)
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.centralWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.artistLabel = QLabel(self.centralWidget)
        self.artistLabel.setObjectName(u"artistLabel")
        self.artistLabel.setGeometry(QRect(80, 350, 331, 31))
        font = QFont()
        font.setFamilies([u"Sans"])
        font.setPointSize(12)
        font.setBold(True)
        self.artistLabel.setFont(font)
        self.artistLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.coverLabel = QLabel(self.centralWidget)
        self.coverLabel.setObjectName(u"coverLabel")
        self.coverLabel.setGeometry(QRect(120, 10, 250, 250))
        self.coverLabel.setAutoFillBackground(False)
        self.coverLabel.setStyleSheet(u"border-radius: 14px;\n"
"")
        self.coverLabel.setPixmap(QPixmap(u":/assets/default-cover.png"))
        self.coverLabel.setScaledContents(False)
        self.coverLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.titleLabel = QLabel(self.centralWidget)
        self.titleLabel.setObjectName(u"titleLabel")
        self.titleLabel.setGeometry(QRect(10, 270, 471, 81))
        font1 = QFont()
        font1.setFamilies([u"System-ui"])
        font1.setPointSize(15)
        font1.setBold(False)
        self.titleLabel.setFont(font1)
        self.titleLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setWordWrap(True)
        self.progressLabel = QLabel(self.centralWidget)
        self.progressLabel.setObjectName(u"progressLabel")
        self.progressLabel.setGeometry(QRect(60, 400, 71, 20))
        font2 = QFont()
        font2.setPointSize(11)
        self.progressLabel.setFont(font2)
        self.progressLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.durationLabel = QLabel(self.centralWidget)
        self.durationLabel.setObjectName(u"durationLabel")
        self.durationLabel.setGeometry(QRect(370, 400, 71, 18))
        self.durationLabel.setFont(font2)
        self.durationLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.progressSlider = QSlider(self.centralWidget)
        self.progressSlider.setObjectName(u"progressSlider")
        self.progressSlider.setEnabled(False)
        self.progressSlider.setGeometry(QRect(140, 400, 221, 20))
        self.progressSlider.setOrientation(Qt.Orientation.Horizontal)
        self.previousButton = QPushButton(self.centralWidget)
        self.previousButton.setObjectName(u"previousButton")
        self.previousButton.setGeometry(QRect(130, 440, 86, 51))
        self.previousButton.setIcon(icon4)
        self.previousButton.setIconSize(QSize(32, 32))
        self.previousButton.setFlat(True)
        self.playButton = QPushButton(self.centralWidget)
        self.playButton.setObjectName(u"playButton")
        self.playButton.setGeometry(QRect(210, 420, 86, 81))
        self.playButton.setIcon(icon3)
        self.playButton.setIconSize(QSize(56, 56))
        self.playButton.setFlat(True)
        self.nextButton = QPushButton(self.centralWidget)
        self.nextButton.setObjectName(u"nextButton")
        self.nextButton.setGeometry(QRect(290, 440, 86, 51))
        self.nextButton.setIcon(icon5)
        self.nextButton.setIconSize(QSize(32, 32))
        self.nextButton.setFlat(True)
        self.volumeSlider = QSlider(self.centralWidget)
        self.volumeSlider.setObjectName(u"volumeSlider")
        self.volumeSlider.setEnabled(True)
        self.volumeSlider.setGeometry(QRect(140, 540, 221, 31))
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setValue(50)
        self.volumeSlider.setTracking(True)
        self.volumeSlider.setOrientation(Qt.Orientation.Horizontal)
        self.volumeButton = QPushButton(self.centralWidget)
        self.volumeButton.setObjectName(u"volumeButton")
        self.volumeButton.setGeometry(QRect(100, 540, 31, 26))
        icon7 = QIcon()
        icon7.addFile(u":/assets/volume.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.volumeButton.setIcon(icon7)
        self.volumeButton.setIconSize(QSize(24, 24))
        self.volumeButton.setAutoDefault(False)
        self.volumeButton.setFlat(True)
        self.volumeLabel = QLabel(self.centralWidget)
        self.volumeLabel.setObjectName(u"volumeLabel")
        self.volumeLabel.setGeometry(QRect(370, 540, 41, 20))
        self.volumeLabel.setFont(font2)
        self.volumeLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 485, 23))
        self.menuBar.setDefaultUp(False)
        self.menuMedia = QMenu(self.menuBar)
        self.menuMedia.setObjectName(u"menuMedia")
        self.menuPlaying = QMenu(self.menuBar)
        self.menuPlaying.setObjectName(u"menuPlaying")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.menuBar.addAction(self.menuMedia.menuAction())
        self.menuBar.addAction(self.menuPlaying.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuMedia.addAction(self.actionOpenFile)
        self.menuMedia.addAction(self.actionOpenFolder)
        self.menuMedia.addAction(self.actionQuit)
        self.menuPlaying.addAction(self.actionPlay)
        self.menuPlaying.addAction(self.actionPrevious)
        self.menuPlaying.addAction(self.actionNext)
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        self.previousButton.setDefault(True)
        self.playButton.setDefault(True)
        self.nextButton.setDefault(True)
        self.volumeButton.setDefault(True)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"PyPlayer", None))
        self.actionOpenFile.setText(QCoreApplication.translate("MainWindow", u"Abrir archivo", None))
        self.actionOpenFolder.setText(QCoreApplication.translate("MainWindow", u"Abrir carpeta", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
        self.actionPlay.setText(QCoreApplication.translate("MainWindow", u"Reproducir", None))
        self.actionPrevious.setText(QCoreApplication.translate("MainWindow", u"Anterior", None))
        self.actionPrevious.setIconText(QCoreApplication.translate("MainWindow", u"Anterior", None))
        self.actionNext.setText(QCoreApplication.translate("MainWindow", u"Siguiente", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"Acerca de", None))
        self.artistLabel.setText(QCoreApplication.translate("MainWindow", u"Artista Desconocido", None))
        self.coverLabel.setText("")
        self.titleLabel.setText(QCoreApplication.translate("MainWindow", u"Sin t\u00edtulo", None))
        self.progressLabel.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.durationLabel.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.previousButton.setText("")
        self.playButton.setText("")
        self.nextButton.setText("")
        self.volumeButton.setText("")
        self.volumeLabel.setText(QCoreApplication.translate("MainWindow", u"50%", None))
        self.menuMedia.setTitle(QCoreApplication.translate("MainWindow", u"Medio", None))
        self.menuPlaying.setTitle(QCoreApplication.translate("MainWindow", u"Reproducci\u00f3n", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Ayuda", None))
    # retranslateUi
